/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : Principal,
  'status' : AgentStatus,
  'name' : string,
  'mobile' : string,
  'photo' : ExternalBlob,
}
export type AgentStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null } |
  { 'rejected' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface FollowUp {
  'id' : bigint,
  'status' : FollowUpStatus,
  'date' : bigint,
  'agentId' : Principal,
  'taskType' : string,
  'leadId' : bigint,
  'priority' : string,
  'amount' : bigint,
  'remarks' : string,
}
export type FollowUpStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'overdue' : null };
export interface Lead {
  'id' : bigint,
  'status' : string,
  'leadType' : LeadType,
  'propertyType' : PropertyType,
  'source' : string,
  'assignedAgent' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'leadLevel' : string,
  'mobile' : string,
  'price' : bigint,
  'requirements' : [] | [string],
}
export type LeadType = { 'rent' : null } |
  { 'sale' : null };
export interface Owner {
  'id' : bigint,
  'propertyType' : PropertyType,
  'name' : string,
  'agentCommission' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'address' : string,
  'mobile' : string,
  'price' : bigint,
  'location' : string,
  'remarks' : string,
  'verificationStatus' : string,
}
export type PropertyType = { 'commercial' : null } |
  { 'house' : null } |
  { 'land' : null } |
  { 'apartment' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgent' : ActorMethod<[string, string, ExternalBlob], Principal>,
  'createFollowUp' : ActorMethod<
    [bigint, FollowUpStatus, string, bigint, string, string, bigint],
    bigint
  >,
  'createLead' : ActorMethod<
    [
      string,
      string,
      PropertyType,
      LeadType,
      bigint,
      Principal,
      string,
      string,
      string,
      [] | [string],
    ],
    bigint
  >,
  'createOwner' : ActorMethod<
    [
      string,
      string,
      PropertyType,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'deleteFollowUp' : ActorMethod<[bigint], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteOwner' : ActorMethod<[bigint], undefined>,
  'getAgentDetails' : ActorMethod<[Principal], Agent>,
  'getAgentFollowUps' : ActorMethod<[Principal], Array<FollowUp>>,
  'getAgentLeads' : ActorMethod<[Principal], Array<Lead>>,
  'getAgentOwners' : ActorMethod<[Principal], Array<Owner>>,
  'getAllAgents' : ActorMethod<[], Array<Agent>>,
  'getAllFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllOwners' : ActorMethod<[], Array<Owner>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[bigint], Lead>,
  'getOwner' : ActorMethod<[bigint], Owner>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateAgentStatus' : ActorMethod<[Principal, AgentStatus], undefined>,
  'updateFollowUp' : ActorMethod<
    [bigint, FollowUpStatus, string, bigint, string, string, bigint],
    undefined
  >,
  'updateLead' : ActorMethod<
    [
      bigint,
      string,
      string,
      PropertyType,
      LeadType,
      bigint,
      Principal,
      string,
      string,
      string,
      [] | [string],
    ],
    undefined
  >,
  'updateOwner' : ActorMethod<
    [
      bigint,
      string,
      string,
      PropertyType,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];