/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FollowUpStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'house' : IDL.Null,
  'land' : IDL.Null,
  'apartment' : IDL.Null,
});
export const LeadType = IDL.Variant({ 'rent' : IDL.Null, 'sale' : IDL.Null });
export const AgentStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Agent = IDL.Record({
  'id' : IDL.Principal,
  'status' : AgentStatus,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
  'photo' : ExternalBlob,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Nat,
  'status' : FollowUpStatus,
  'date' : IDL.Int,
  'agentId' : IDL.Principal,
  'taskType' : IDL.Text,
  'leadId' : IDL.Nat,
  'priority' : IDL.Text,
  'amount' : IDL.Nat,
  'remarks' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'leadType' : LeadType,
  'propertyType' : PropertyType,
  'source' : IDL.Text,
  'assignedAgent' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'leadLevel' : IDL.Text,
  'mobile' : IDL.Text,
  'price' : IDL.Nat,
  'requirements' : IDL.Opt(IDL.Text),
});
export const Owner = IDL.Record({
  'id' : IDL.Nat,
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'agentCommission' : IDL.Nat,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'remarks' : IDL.Text,
  'verificationStatus' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgent' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Principal],
      [],
    ),
  'createFollowUp' : IDL.Func(
      [IDL.Nat, FollowUpStatus, IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PropertyType,
        LeadType,
        IDL.Nat,
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createOwner' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteFollowUp' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteOwner' : IDL.Func([IDL.Nat], [], []),
  'getAgentDetails' : IDL.Func([IDL.Principal], [Agent], ['query']),
  'getAgentFollowUps' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FollowUp)],
      ['query'],
    ),
  'getAgentLeads' : IDL.Func([IDL.Principal], [IDL.Vec(Lead)], ['query']),
  'getAgentOwners' : IDL.Func([IDL.Principal], [IDL.Vec(Owner)], ['query']),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllOwners' : IDL.Func([], [IDL.Vec(Owner)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getOwner' : IDL.Func([IDL.Nat], [Owner], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateAgentStatus' : IDL.Func([IDL.Principal, AgentStatus], [], []),
  'updateFollowUp' : IDL.Func(
      [IDL.Nat, FollowUpStatus, IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        PropertyType,
        LeadType,
        IDL.Nat,
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateOwner' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        PropertyType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FollowUpStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'house' : IDL.Null,
    'land' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const LeadType = IDL.Variant({ 'rent' : IDL.Null, 'sale' : IDL.Null });
  const AgentStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Agent = IDL.Record({
    'id' : IDL.Principal,
    'status' : AgentStatus,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Nat,
    'status' : FollowUpStatus,
    'date' : IDL.Int,
    'agentId' : IDL.Principal,
    'taskType' : IDL.Text,
    'leadId' : IDL.Nat,
    'priority' : IDL.Text,
    'amount' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'leadType' : LeadType,
    'propertyType' : PropertyType,
    'source' : IDL.Text,
    'assignedAgent' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'leadLevel' : IDL.Text,
    'mobile' : IDL.Text,
    'price' : IDL.Nat,
    'requirements' : IDL.Opt(IDL.Text),
  });
  const Owner = IDL.Record({
    'id' : IDL.Nat,
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'agentCommission' : IDL.Nat,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'remarks' : IDL.Text,
    'verificationStatus' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgent' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Principal],
        [],
      ),
    'createFollowUp' : IDL.Func(
        [
          IDL.Nat,
          FollowUpStatus,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PropertyType,
          LeadType,
          IDL.Nat,
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createOwner' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteFollowUp' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteOwner' : IDL.Func([IDL.Nat], [], []),
    'getAgentDetails' : IDL.Func([IDL.Principal], [Agent], ['query']),
    'getAgentFollowUps' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'getAgentLeads' : IDL.Func([IDL.Principal], [IDL.Vec(Lead)], ['query']),
    'getAgentOwners' : IDL.Func([IDL.Principal], [IDL.Vec(Owner)], ['query']),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllOwners' : IDL.Func([], [IDL.Vec(Owner)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getOwner' : IDL.Func([IDL.Nat], [Owner], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateAgentStatus' : IDL.Func([IDL.Principal, AgentStatus], [], []),
    'updateFollowUp' : IDL.Func(
        [
          IDL.Nat,
          FollowUpStatus,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          PropertyType,
          LeadType,
          IDL.Nat,
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateOwner' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          PropertyType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };