/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Agent {
    id: Principal;
    status: AgentStatus;
    name: string;
    mobile: string;
    photo: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lead {
    id: bigint;
    status: string;
    leadType: LeadType;
    propertyType: PropertyType;
    source: string;
    assignedAgent: Principal;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    leadLevel: string;
    mobile: string;
    price: bigint;
    requirements?: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface FollowUp {
    id: bigint;
    status: FollowUpStatus;
    date: bigint;
    agentId: Principal;
    taskType: string;
    leadId: bigint;
    priority: string;
    amount: bigint;
    remarks: string;
}
export interface Owner {
    id: bigint;
    propertyType: PropertyType;
    name: string;
    agentCommission: bigint;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    mobile: string;
    price: bigint;
    location: string;
    remarks: string;
    verificationStatus: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum AgentStatus {
    active = "active",
    pending = "pending",
    inactive = "inactive",
    rejected = "rejected"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum FollowUpStatus {
    pending = "pending",
    completed = "completed",
    overdue = "overdue"
}
export enum LeadType {
    rent = "rent",
    sale = "sale"
}
export enum PropertyType {
    commercial = "commercial",
    house = "house",
    land = "land",
    apartment = "apartment"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAgent(name: string, mobile: string, photo: ExternalBlob): Promise<Principal>;
    createFollowUp(leadId: bigint, status: FollowUpStatus, remarks: string, date: bigint, priority: string, taskType: string, amount: bigint): Promise<bigint>;
    createLead(name: string, mobile: string, propertyType: PropertyType, leadType: LeadType, price: bigint, assignedAgent: Principal, leadLevel: string, source: string, status: string, requirements: string | null): Promise<bigint>;
    createOwner(name: string, mobile: string, propertyType: PropertyType, location: string, verificationStatus: string, price: bigint, agentCommission: bigint, remarks: string, address: string): Promise<bigint>;
    deleteFollowUp(followUpId: bigint): Promise<void>;
    deleteLead(leadId: bigint): Promise<void>;
    deleteOwner(ownerId: bigint): Promise<void>;
    getAgentDetails(agentId: Principal): Promise<Agent>;
    getAgentFollowUps(agentId: Principal): Promise<Array<FollowUp>>;
    getAgentLeads(agentId: Principal): Promise<Array<Lead>>;
    getAgentOwners(agentId: Principal): Promise<Array<Owner>>;
    getAllAgents(): Promise<Array<Agent>>;
    getAllFollowUps(): Promise<Array<FollowUp>>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllOwners(): Promise<Array<Owner>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLead(leadId: bigint): Promise<Lead>;
    getOwner(ownerId: bigint): Promise<Owner>;
    getPendingAgents(): Promise<Array<Agent>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    registerAsAgent(name: string, mobile: string, photo: ExternalBlob): Promise<Principal>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateAgentStatus(agentId: Principal, status: AgentStatus): Promise<void>;
    updateFollowUp(followUpId: bigint, status: FollowUpStatus, remarks: string, date: bigint, priority: string, taskType: string, amount: bigint): Promise<void>;
    updateLead(leadId: bigint, name: string, mobile: string, propertyType: PropertyType, leadType: LeadType, price: bigint, assignedAgent: Principal, leadLevel: string, source: string, status: string, requirements: string | null): Promise<void>;
    updateOwner(ownerId: bigint, name: string, mobile: string, propertyType: PropertyType, location: string, verificationStatus: string, price: bigint, agentCommission: bigint, remarks: string, address: string): Promise<void>;
}
import type { Agent as _Agent, AgentStatus as _AgentStatus, ApprovalStatus as _ApprovalStatus, ExternalBlob as _ExternalBlob, FollowUp as _FollowUp, FollowUpStatus as _FollowUpStatus, Lead as _Lead, LeadType as _LeadType, Owner as _Owner, PropertyType as _PropertyType, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAgent(arg0: string, arg1: string, arg2: ExternalBlob): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgent(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgent(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createFollowUp(arg0: bigint, arg1: FollowUpStatus, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowUp(arg0, to_candid_FollowUpStatus_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowUp(arg0, to_candid_FollowUpStatus_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createLead(arg0: string, arg1: string, arg2: PropertyType, arg3: LeadType, arg4: bigint, arg5: Principal, arg6: string, arg7: string, arg8: string, arg9: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg2), to_candid_LeadType_n15(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg2), to_candid_LeadType_n15(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async createOwner(arg0: string, arg1: string, arg2: PropertyType, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOwner(arg0, arg1, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOwner(arg0, arg1, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteFollowUp(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteOwner(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOwner(arg0);
            return result;
        }
    }
    async getAgentDetails(arg0: Principal): Promise<Agent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentDetails(arg0);
                return from_candid_Agent_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentDetails(arg0);
            return from_candid_Agent_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentFollowUps(arg0: Principal): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentFollowUps(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentFollowUps(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentLeads(arg0: Principal): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentLeads(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentLeads(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentOwners(arg0: Principal): Promise<Array<Owner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentOwners(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentOwners(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgents();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgents();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFollowUps();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFollowUps();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOwners(): Promise<Array<Owner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOwners();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOwners();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: bigint): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_Lead_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_Lead_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwner(arg0: bigint): Promise<Owner> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwner(arg0);
                return from_candid_Owner_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwner(arg0);
            return from_candid_Owner_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingAgents();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingAgents();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsAgent(arg0: string, arg1: string, arg2: ExternalBlob): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsAgent(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsAgent(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateAgentStatus(arg0: Principal, arg1: AgentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgentStatus(arg0, to_candid_AgentStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgentStatus(arg0, to_candid_AgentStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFollowUp(arg0: bigint, arg1: FollowUpStatus, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUp(arg0, to_candid_FollowUpStatus_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUp(arg0, to_candid_FollowUpStatus_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: PropertyType, arg4: LeadType, arg5: bigint, arg6: Principal, arg7: string, arg8: string, arg9: string, arg10: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg3), to_candid_LeadType_n15(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg3), to_candid_LeadType_n15(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async updateOwner(arg0: bigint, arg1: string, arg2: string, arg3: PropertyType, arg4: string, arg5: string, arg6: bigint, arg7: bigint, arg8: string, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOwner(arg0, arg1, arg2, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOwner(arg0, arg1, arg2, to_candid_PropertyType_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
}
function from_candid_AgentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_Agent_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Promise<Agent> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FollowUpStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUpStatus): FollowUpStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUp_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUp): FollowUp {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_LeadType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadType): LeadType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Owner_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Owner): Owner {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: _AgentStatus;
    name: string;
    mobile: string;
    photo: _ExternalBlob;
}): Promise<{
    id: Principal;
    status: AgentStatus;
    name: string;
    mobile: string;
    photo: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_AgentStatus_n20(_uploadFile, _downloadFile, value.status),
        name: value.name,
        mobile: value.mobile,
        photo: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.photo)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _FollowUpStatus;
    date: bigint;
    agentId: Principal;
    taskType: string;
    leadId: bigint;
    priority: string;
    amount: bigint;
    remarks: string;
}): {
    id: bigint;
    status: FollowUpStatus;
    date: bigint;
    agentId: Principal;
    taskType: string;
    leadId: bigint;
    priority: string;
    amount: bigint;
    remarks: string;
} {
    return {
        id: value.id,
        status: from_candid_FollowUpStatus_n26(_uploadFile, _downloadFile, value.status),
        date: value.date,
        agentId: value.agentId,
        taskType: value.taskType,
        leadId: value.leadId,
        priority: value.priority,
        amount: value.amount,
        remarks: value.remarks
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    leadType: _LeadType;
    propertyType: _PropertyType;
    source: string;
    assignedAgent: Principal;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    leadLevel: string;
    mobile: string;
    price: bigint;
    requirements: [] | [string];
}): {
    id: bigint;
    status: string;
    leadType: LeadType;
    propertyType: PropertyType;
    source: string;
    assignedAgent: Principal;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    leadLevel: string;
    mobile: string;
    price: bigint;
    requirements?: string;
} {
    return {
        id: value.id,
        status: value.status,
        leadType: from_candid_LeadType_n31(_uploadFile, _downloadFile, value.leadType),
        propertyType: from_candid_PropertyType_n33(_uploadFile, _downloadFile, value.propertyType),
        source: value.source,
        assignedAgent: value.assignedAgent,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        leadLevel: value.leadLevel,
        mobile: value.mobile,
        price: value.price,
        requirements: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.requirements))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    propertyType: _PropertyType;
    name: string;
    agentCommission: bigint;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    mobile: string;
    price: bigint;
    location: string;
    remarks: string;
    verificationStatus: string;
}): {
    id: bigint;
    propertyType: PropertyType;
    name: string;
    agentCommission: bigint;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    mobile: string;
    price: bigint;
    location: string;
    remarks: string;
    verificationStatus: string;
} {
    return {
        id: value.id,
        propertyType: from_candid_PropertyType_n33(_uploadFile, _downloadFile, value.propertyType),
        name: value.name,
        agentCommission: value.agentCommission,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        address: value.address,
        mobile: value.mobile,
        price: value.price,
        location: value.location,
        remarks: value.remarks,
        verificationStatus: value.verificationStatus
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n46(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} | {
    rejected: null;
}): AgentStatus {
    return "active" in value ? AgentStatus.active : "pending" in value ? AgentStatus.pending : "inactive" in value ? AgentStatus.inactive : "rejected" in value ? AgentStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
}): FollowUpStatus {
    return "pending" in value ? FollowUpStatus.pending : "completed" in value ? FollowUpStatus.completed : "overdue" in value ? FollowUpStatus.overdue : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rent: null;
} | {
    sale: null;
}): LeadType {
    return "rent" in value ? LeadType.rent : "sale" in value ? LeadType.sale : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    house: null;
} | {
    land: null;
} | {
    apartment: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "house" in value ? PropertyType.house : "land" in value ? PropertyType.land : "apartment" in value ? PropertyType.apartment : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUp>): Array<FollowUp> {
    return value.map((x)=>from_candid_FollowUp_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Owner>): Array<Owner> {
    return value.map((x)=>from_candid_Owner_n37(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Promise<Array<Agent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Agent_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n44(_uploadFile, _downloadFile, x));
}
function to_candid_AgentStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): _AgentStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FollowUpStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpStatus): _FollowUpStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_LeadType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadType): _LeadType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpStatus): {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} {
    return value == FollowUpStatus.pending ? {
        pending: null
    } : value == FollowUpStatus.completed ? {
        completed: null
    } : value == FollowUpStatus.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    house: null;
} | {
    land: null;
} | {
    apartment: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.house ? {
        house: null
    } : value == PropertyType.land ? {
        land: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadType): {
    rent: null;
} | {
    sale: null;
} {
    return value == LeadType.rent ? {
        rent: null
    } : value == LeadType.sale ? {
        sale: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} | {
    rejected: null;
} {
    return value == AgentStatus.active ? {
        active: null
    } : value == AgentStatus.pending ? {
        pending: null
    } : value == AgentStatus.inactive ? {
        inactive: null
    } : value == AgentStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
